name: Build AndUEDumper (Fixed)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AndUEDumper

    steps:
      - name: 拉取代码（含子模块）
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 安装兼容版本 NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e  # 优先尝试旧版本

      - name: 验证环境
        run: |
          echo "NDK路径: $NDK_HOME"
          ls -l jni/  # 检查配置文件是否存在

      - name: 强制赋予脚本权限
        run: chmod 777 ndk-build.sh

      - name: 执行编译（带详细日志）
        run: ./ndk-build.sh V=1  # V=1 输出详细编译日志，方便排查

      - name: 打包产物
        if: success()  # 仅成功时执行
        run: |
          mkdir -p ../../output
          cp -r build/libs/* ../../output/

      - name: 上传产物
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: AndUEDumper-Builds
          path: output/
